In [1]:
# torch.nn.RNNCell( ) 和torch.nn.RNN()
# 区别在于RNNCell() 只能接受序列中单步的输入，且必须传入隐藏状态，
#而RNN 可以接受一个序列的输入，默认会传入全0的隐藏状态，也可以自己申明隐藏状态的传入

#RNN() 里面的参数有
# input_size() 表示输入xt的特征维度
#hidden_size() 表示输出特征的的维度
#num_layers 表示网络的层数
#nonlinearity 表示选用的非线性激活函数，默认tanh
#bias 表示是否使用偏置，默认使用
# batch_first 表示输入数据的形式，默认是False，就是这样的形式，(seq,batch,feature),也就是，(seq,batch,feature) # 也就是将序列长度放在第一位，
#batch 放在第二位
#dropout 表示是否在输出层应用dropout
# bidirectional 表示是否使用双向的rnn，默认是False
# 对于RNNCell ,里面的参数就少很多，input size ，hidden size，bias 以及nonlinearity

In [8]:
import torch
from torch.autograd import Variable

from torch import nn
# 定义一个 单位的rnn
rnn_single=nn.RNNCell(input_size=100,hidden_size=200)
# 访问其中的参数
rnn_single.weight_hh

Parameter containing:
tensor([[ 0.0639,  0.0270, -0.0035,  ...,  0.0620, -0.0691, -0.0372],
        [-0.0646,  0.0118, -0.0168,  ..., -0.0636, -0.0085, -0.0300],
        [-0.0555, -0.0652,  0.0159,  ..., -0.0268, -0.0514, -0.0358],
        ...,
        [ 0.0235,  0.0539, -0.0508,  ...,  0.0704, -0.0292, -0.0405],
        [ 0.0376, -0.0112, -0.0521,  ..., -0.0699, -0.0040, -0.0471],
        [-0.0082,  0.0531,  0.0577,  ..., -0.0558,  0.0531, -0.0072]],
       requires_grad=True)

In [9]:
# 构造一个序列，长为6，batch 是5，特征是100
x=Variable(torch.randn(6,5,100))  # 这是rnn 的输入格式
x

tensor([[[-0.5462, -0.1716, -0.5996,  ..., -0.8690, -0.3007,  0.2606],
         [-0.1988, -0.7967,  0.7161,  ..., -1.0914,  0.4955,  0.8545],
         [ 1.3151, -2.0528, -0.8196,  ...,  1.2931,  0.0623, -0.9648],
         [-0.5227,  0.1071, -1.0059,  ..., -0.6704,  0.1640, -0.2296],
         [-0.2743,  0.3943, -0.7424,  ...,  0.1958,  0.9897, -0.4850]],

        [[-0.0150, -0.9587, -0.4893,  ...,  0.2075,  1.2332,  1.7170],
         [ 0.7711,  0.7815,  1.3234,  ...,  0.6530, -0.3418,  0.4617],
         [-0.6770, -2.5524,  1.1276,  ..., -0.9675,  1.5249, -1.0309],
         [-0.5106,  0.1699,  2.1879,  ...,  1.4807, -2.0397,  0.3809],
         [-0.0328, -0.5318,  0.0296,  ...,  0.2609, -0.8509,  0.5392]],

        [[ 0.2974, -1.4286, -1.8997,  ..., -0.4913,  1.2070,  0.0621],
         [ 1.3886, -0.9220,  0.0168,  ...,  0.4050,  2.5153, -1.2488],
         [ 1.5540, -0.1295,  0.5015,  ...,  0.5670, -1.4137, -0.7804],
         [-1.1179,  1.7208, -2.4872,  ..., -0.9658,  0.2378,  0.2757],
  

In [10]:
h_t=Variable(torch.zeros(5,200)) # 定义初始的记忆状态

In [11]:
# 传入rnn
out=[]
for i in range(6): # 通过循环6 次作用在整个序列上
    h_t=rnn_single(x[i],h_t)
    out.append(h_t)

In [12]:
h_t

tensor([[ 2.5115e-01,  1.9233e-01, -2.2090e-01,  3.8104e-01, -4.2449e-01,
          2.5965e-01, -2.0136e-01,  7.6212e-01, -2.3776e-01, -4.4887e-01,
         -3.2697e-01, -4.4931e-01, -4.7575e-01,  3.3408e-01,  2.5274e-01,
         -2.6966e-01,  4.0051e-03,  3.4040e-01,  5.6579e-01, -1.3347e-01,
          1.7116e-01, -2.5172e-01,  2.2801e-01, -2.8386e-01,  1.1397e-01,
         -5.5833e-01,  8.3125e-02,  4.7818e-01, -3.5754e-01,  3.8459e-01,
         -1.9156e-01, -1.8955e-01, -9.1613e-02,  4.9145e-01, -2.9965e-01,
         -2.3465e-01,  7.7710e-02,  8.0806e-01, -3.9744e-01, -5.4176e-01,
          2.6857e-02,  6.1968e-01,  3.8015e-01, -1.1984e-01,  7.6234e-02,
          4.0348e-02,  2.5157e-01,  2.4889e-01,  3.8703e-01,  7.6906e-01,
          2.9721e-01,  5.3965e-02, -5.3957e-01, -1.2349e-01, -1.7122e-01,
          8.6020e-02, -7.4094e-02, -4.9960e-02, -1.8609e-01, -6.2580e-01,
         -3.3321e-01,  9.0537e-02, -1.6221e-01, -2.9381e-02,  4.0941e-02,
         -4.9797e-01,  1.3608e-01, -1.

In [13]:
len(out)

6

In [14]:
out[0].shape # 每个输出的维度

torch.Size([5, 200])

In [ ]:
# 经过了rnn 之后，隐藏状态的值已经被改变了，因为网络记忆了序列中的信息，同时输出6个结果

In [26]:
rnn_seq=nn.RNN(100,200)

In [27]:
out,h_t =rnn_seq(x) # 使用默认的全 隐藏状态
h_t

tensor([[[-2.6095e-01, -4.9760e-01,  4.2013e-01,  7.2525e-01, -9.1272e-02,
          -7.3611e-02, -3.6429e-02,  6.7707e-01,  2.4478e-01,  2.4115e-01,
          -6.0709e-01, -2.3626e-01, -1.0078e-01, -2.6287e-01, -1.4811e-01,
          -5.3297e-01, -2.6885e-03,  2.1705e-01,  5.5205e-01,  6.2379e-01,
           4.8095e-01,  3.0965e-01, -3.2376e-01,  3.3627e-01, -4.2168e-01,
          -4.2898e-02,  1.7808e-01, -2.3285e-01,  3.8955e-01,  1.6265e-01,
           4.3288e-02,  2.4128e-01, -4.0887e-01,  3.6240e-01, -3.0752e-01,
           2.2824e-02, -1.8200e-01,  1.4402e-01,  7.6567e-01,  5.0293e-01,
           4.9030e-01, -4.9916e-01, -5.2324e-01, -1.9253e-01, -3.1542e-01,
          -5.6903e-01, -3.4738e-01,  1.6740e-01,  5.6982e-02, -6.3843e-02,
           1.1219e-02,  1.0522e-02,  2.0084e-01,  3.9201e-01,  5.9712e-01,
          -1.5027e-01,  3.8301e-01, -1.3096e-01,  2.3138e-01,  5.8388e-01,
          -2.6876e-01, -1.0419e-01, -5.1992e-01, -6.2836e-01,  2.1119e-01,
           8.0261e-01,  1

In [28]:
# 自己定义的初始的隐藏状态
h_0=Variable(torch.randn(1,5,200))# 有三个维度，分别是(num_layer* num_direction,batch,hidden_size)

In [30]:
out,h_t=rnn_seq(x,h_0)

In [31]:
h_t

tensor([[[-2.7413e-01, -4.8455e-01,  4.3525e-01,  7.2141e-01, -7.3740e-02,
          -6.2501e-02, -1.6344e-02,  6.7207e-01,  2.3084e-01,  2.4149e-01,
          -5.9491e-01, -2.2764e-01, -1.0869e-01, -2.6065e-01, -1.4987e-01,
          -5.1816e-01, -5.1752e-03,  2.2736e-01,  5.6165e-01,  6.2816e-01,
           4.9688e-01,  2.9799e-01, -3.4772e-01,  3.4688e-01, -4.2645e-01,
          -3.3411e-02,  1.8536e-01, -2.3961e-01,  3.8300e-01,  1.7665e-01,
           2.2127e-02,  2.2774e-01, -4.0086e-01,  3.7544e-01, -3.0148e-01,
           3.2389e-02, -1.8641e-01,  1.5129e-01,  7.6711e-01,  5.1189e-01,
           4.8598e-01, -4.9090e-01, -5.3275e-01, -2.0333e-01, -3.2156e-01,
          -5.6562e-01, -3.4914e-01,  1.5179e-01,  5.7146e-02, -6.7624e-02,
           4.4759e-03,  2.4029e-03,  1.8569e-01,  3.9208e-01,  6.0169e-01,
          -1.5611e-01,  3.9514e-01, -1.2975e-01,  2.4288e-01,  5.8266e-01,
          -2.5395e-01, -1.1647e-01, -5.2916e-01, -6.1808e-01,  1.9832e-01,
           8.0727e-01,  8

In [32]:
out.shape

torch.Size([6, 5, 200])

In [33]:
# 输出的结果也是(seq,batch,feature)
# 一般使用nn.RNN() ，能避免我们手动写循环，非常方便，，同时如果不特别说明，也会使用默认的全0 初始化隐藏状态

In [34]:
#（2） LSTM 有nn.LSTMCell() 和nn.LSTM() 两种形式
lstm_seq=nn.LSTM(50,100,num_layers=2) # 输入维度100，输出200，两层
lstm_seq.weight_hh_l0 # 第一层的h_t 权重


Parameter containing:
tensor([[ 0.0703,  0.0436, -0.0250,  ..., -0.0641, -0.0587, -0.0526],
        [ 0.0352,  0.0630,  0.0337,  ...,  0.0096,  0.0295, -0.0021],
        [ 0.0831,  0.0193,  0.0148,  ..., -0.0870,  0.0864, -0.0298],
        ...,
        [-0.0684,  0.0272,  0.0163,  ..., -0.0645,  0.0235, -0.0050],
        [ 0.0408,  0.0617,  0.0568,  ...,  0.0916, -0.0768, -0.0520],
        [ 0.0032,  0.0657,  0.0830,  ...,  0.0080, -0.0621, -0.0926]],
       requires_grad=True)

In [36]:
lstm_input=Variable(torch.randn(10,3,50))# 序列是10，batch 为3，输入维度是50
out,(h,c)=lstm_seq(lstm_input) # 使用默认的全0 状态
# h和c 都是隐藏状态，大小相同，（num_layers*direction,batch,feature）

In [37]:
h.shape# 两层，Batch 是3，特征是100

torch.Size([2, 3, 100])

In [38]:
c.shape

torch.Size([2, 3, 100])

In [39]:
out.shape

torch.Size([10, 3, 100])

In [40]:
# 可以不使用 默认的隐藏状态，这是需要传入两个张量
h_init=Variable(torch.randn(2,3,100))
c_init=Variable(torch.randn(2,3,100))
out,(h,c)=lstm_seq(lstm_input,(h_init,c_init))
h.shape

torch.Size([2, 3, 100])

In [41]:
c.shape

torch.Size([2, 3, 100])

In [42]:
out.shape

torch.Size([10, 3, 100])

In [43]:
#(3) GRU
gru_seq=nn.GRU(10,20)
gru_input=Variable(torch.randn(3,32,10))
out,h=gru_seq(gru_input)
gru_seq.weight_hh_l0

Parameter containing:
tensor([[ 0.1402,  0.0444,  0.0207,  ..., -0.1646, -0.1350,  0.0009],
        [-0.0053,  0.1773,  0.1886,  ...,  0.0865, -0.1541, -0.2119],
        [-0.0801,  0.2158, -0.0515,  ...,  0.1396, -0.0663, -0.0182],
        ...,
        [-0.2020,  0.0142, -0.0116,  ..., -0.0152, -0.2078,  0.0123],
        [ 0.1736, -0.0249,  0.1994,  ...,  0.1126, -0.1047, -0.0131],
        [-0.0639,  0.0616, -0.0147,  ...,  0.2120,  0.0012, -0.1490]],
       requires_grad=True)

In [44]:
h.shape

torch.Size([1, 32, 20])

In [45]:
out.shape

torch.Size([3, 32, 20])