In [2]:
import torch
from torch.autograd import Variable


In [5]:
#（1） 简单情况的自动求导
x=Variable(torch.Tensor([2]),requires_grad=True)
y=x+2
z=y**2+3
z

tensor([19.], grad_fn=<AddBackward0>)

In [ ]:
#从z 对x 求导 为8

In [6]:
z.backward()
print(x.grad)

tensor([8.])


In [7]:
# 2 更复杂的例子
x=Variable(torch.randn(10,20),requires_grad=True)
y=Variable(torch.randn(10,5),requires_grad=True)
w=Variable(torch.randn(20,5),requires_grad=True)
out=torch.mean(y-torch.matmul(x,w)) # torch.matmul 是做矩阵乘法
out.backward()


In [8]:
# x 的梯度
print(x.grad)

tensor([[-0.0205,  0.0497, -0.0509,  0.0060, -0.0283,  0.0112,  0.0205, -0.1640,
         -0.0499,  0.0251, -0.0022,  0.0221,  0.0057, -0.0302,  0.0869, -0.0709,
         -0.0377,  0.1421, -0.0272,  0.0669],
        [-0.0205,  0.0497, -0.0509,  0.0060, -0.0283,  0.0112,  0.0205, -0.1640,
         -0.0499,  0.0251, -0.0022,  0.0221,  0.0057, -0.0302,  0.0869, -0.0709,
         -0.0377,  0.1421, -0.0272,  0.0669],
        [-0.0205,  0.0497, -0.0509,  0.0060, -0.0283,  0.0112,  0.0205, -0.1640,
         -0.0499,  0.0251, -0.0022,  0.0221,  0.0057, -0.0302,  0.0869, -0.0709,
         -0.0377,  0.1421, -0.0272,  0.0669],
        [-0.0205,  0.0497, -0.0509,  0.0060, -0.0283,  0.0112,  0.0205, -0.1640,
         -0.0499,  0.0251, -0.0022,  0.0221,  0.0057, -0.0302,  0.0869, -0.0709,
         -0.0377,  0.1421, -0.0272,  0.0669],
        [-0.0205,  0.0497, -0.0509,  0.0060, -0.0283,  0.0112,  0.0205, -0.1640,
         -0.0499,  0.0251, -0.0022,  0.0221,  0.0057, -0.0302,  0.0869, -0.0709,
      

In [9]:

print(y.grad)

tensor([[0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200],
        [0.0200, 0.0200, 0.0200, 0.0200, 0.0200]])


In [10]:
w.grad

tensor([[-0.0375, -0.0375, -0.0375, -0.0375, -0.0375],
        [ 0.0262,  0.0262,  0.0262,  0.0262,  0.0262],
        [-0.0773, -0.0773, -0.0773, -0.0773, -0.0773],
        [ 0.0150,  0.0150,  0.0150,  0.0150,  0.0150],
        [ 0.1343,  0.1343,  0.1343,  0.1343,  0.1343],
        [-0.0050, -0.0050, -0.0050, -0.0050, -0.0050],
        [-0.0819, -0.0819, -0.0819, -0.0819, -0.0819],
        [-0.0464, -0.0464, -0.0464, -0.0464, -0.0464],
        [ 0.0414,  0.0414,  0.0414,  0.0414,  0.0414],
        [-0.0839, -0.0839, -0.0839, -0.0839, -0.0839],
        [-0.1112, -0.1112, -0.1112, -0.1112, -0.1112],
        [-0.0129, -0.0129, -0.0129, -0.0129, -0.0129],
        [-0.0228, -0.0228, -0.0228, -0.0228, -0.0228],
        [ 0.0201,  0.0201,  0.0201,  0.0201,  0.0201],
        [-0.0099, -0.0099, -0.0099, -0.0099, -0.0099],
        [-0.0363, -0.0363, -0.0363, -0.0363, -0.0363],
        [ 0.0701,  0.0701,  0.0701,  0.0701,  0.0701],
        [-0.1042, -0.1042, -0.1042, -0.1042, -0.1042],
        [-

In [11]:
#（2） 复杂情况的自动求导
m=Variable(torch.FloatTensor([[2,3]]),requires_grad=True)  # 构建一个1*2 的矩阵
n=Variable(torch.zeros(1,2)) 构建相同大小的0 矩阵
print(m)
print(n)

tensor([[2., 3.]], requires_grad=True)
tensor([[0., 0.]])


In [12]:
# 通过m 中的值计算新的n 中的值
n[0,0]=m[0,0]**2
n[0,1]=m[0,1]**3
print(n)


tensor([[ 4., 27.]], grad_fn=<CopySlices>)


In [14]:
# 在pytorch 中 如果要调用自动求导，需要往backward() 中传入一个参数，这个参数的形状和n 一样大
n.backward(torch.ones_like(n)) #将(w0,w1) 取成(1,1)
print(m.grad)

tensor([[ 4., 27.]])


In [15]:
#（3） 多次自动求导
调用两次backward 就会发现程序报错，没有办法再做一次，这是因为pytorch 默认做完一次自动求导后，计算图就被丢弃了，所以两次自动求导需要手动设置一个东西


In [25]:
x=Variable(torch.FloatTensor([3]),requires_grad=True)

In [26]:
y=x*2+x**2+3
y

tensor([18.], grad_fn=<AddBackward0>)

In [27]:
y.backward(retain_graph=True) # 设置retain_graph 为True 来保留计算图
print(x.grad)

tensor([8.])


In [28]:
y.backward() # 再做一次自动求导，这次不保留计算图
x.grad
# 这里的梯度变成了16，因为这里做了

tensor([16.])

In [44]:
# 练习 需要多看
x=Variable(torch.FloatTensor([2,3]),requires_grad=True)
x
k=Variable(torch.zeros(2))
k[0]=x[0]**2 +3*x[1]
k[1]=x[1]**2+2*x[0]
k


tensor([13., 13.], grad_fn=<CopySlices>)

In [45]:
j=torch.zeros(2,2)
k.backward(torch.FloatTensor([1,0]),retain_graph=True)
j[0]=x.grad.data
x.grad.data

tensor([4., 3.])

In [41]:
torch.ones_like(k)

tensor([1., 1.])

In [42]:
torch.FloatTensor([1,0])

tensor([1., 0.])

In [43]:
# 归0 之前求得的梯度
x.grad.data.zero_()

tensor([0., 0.])

In [46]:
k.backward(torch.FloatTensor([0,1]))
j[1]=x.grad.data

In [47]:
j

tensor([[4., 3.],
        [6., 9.]])